ALTER TABLE `Viaje`
  MODIFY COLUMN `origen` VARCHAR(255) NOT NULL,
  MODIFY COLUMN `destino` VARCHAR(255) NOT NULL,
  ADD COLUMN `origen_lat` DOUBLE DEFAULT NULL,
  ADD COLUMN `origen_lon` DOUBLE DEFAULT NULL,
  ADD COLUMN `destino_lat` DOUBLE DEFAULT NULL,
  ADD COLUMN `destino_lon` DOUBLE DEFAULT NULL;
